### ISSUE TITLE
Optional Task: Add eslint into github actions

### ISSUE THREAD

**Issue by karleenmsrichards** [karleenmsrichards/final-project-gp2#52]
**Concepts**

Github Actions: Everytime you push code to github it run tasks and gives you the results. 
- Look atn this article for mayve 30 minutes https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions it is deep, we just need the overview
- Look up the linux concept of $? see https://shapeshed.com/unix-exit-codes/
- Basically every terminal command returns a code which you access from the terminal  with `echo $?`
- 0 is good, any other number is bad
YAML: An alternative to JSON

Google these concept and try and get an understanding

**What to do**

- Make new folder named `.github/workflows` in the root folder
- add a new yaml file called eslint.yaml
```
on:
  push:
name: example
jobs:
  lint:
    name: run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: run lint command
        run: npm run lint
```
- go to this link https://github.com/karleenmsrichards/final-project-gp2/actions/new
- the eslint will run on this page every time you push to any branch
- The above code may not work

**Notes**

Any questions add here
