### ISSUE TITLE
Optional Task: Add npm audit to Github actions

### ISSUE THREAD

**Issue by HeniMKH** [karleenmsrichards/final-project-gp2#83]
**Concepts**

- No new concepts
- We are combining what we did from the prewvious 2 tasks

**Dependencies**

- https://github.com/users/karleenmsrichards/projects/4/views/1?pane=issue&itemId=34789302
- https://github.com/users/karleenmsrichards/projects/4/views/1?pane=issue&itemId=34790669

**Hint**
This page has a config https://github.com/sonatype-nexus-community/example-auditjs-repo/blob/master/.github/workflows/nodejs.yml

```
name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: run auditjs
      run: |
        npx auditjs@beta ossi

```
